const fs = require('fs');

const fileDocs = fs.readFileSync('/home/rebelforce/projects/pingdev/file-docs.md', 'utf-8');

const lines = [
  "# PingOS Codebase Deep Dive",
  "",
  "## Introduction",
  "",
  "PingOS is an ahead-of-time web-to-API compiler that acts as an operating system for the web. It turns any website into a programmable REST API by routing requests through a Chrome MV3 extension bridge to control real browser tabs. This allows developers to reuse existing browser sessions, preserving authentication and context, and bypasses the overhead of launching new headless browsers for every task. The system emphasizes low-latency, deterministic execution at runtime, falling back to LLM-assisted 'self-healing' only when page structures change.",
  "",
  "## Repository Structure",
  "",
  "The project is a monorepo managed by npm workspaces:",
  "",
  "- **`packages/core/`**: `@pingdev/core` - Legacy/Shared PingApp engine structures.",
  "- **`packages/std/`**: `@pingdev/std` - The core of PingOS. Includes the Gateway server, driver registry, extension bridge, pipelines, smart extraction logic, LLM drivers, and app routing.",
  "- **`packages/cli/`**: `pingdev` - CLI entry points for starting the gateway, MCP, or snapshot generation.",
  "- **`packages/mcp-server/`**: Model Context Protocol (MCP) server for Claude Desktop / Cursor integration.",
  "- **`packages/chrome-extension/`**: The Chrome MV3 extension. Includes content scripts, the WebSocket background worker, adblocking logic, and DOM interaction implementations (Ops).",
  "",
  "## Architecture & Data Flow",
  "",
  "### Request Flow",
  "```text",
  "Client (cURL, Agent, Python SDK, MCP)",
  "  | ",
  "  v",
  "Gateway (Fastify HTTP :3500) ---> [App Routes / Functions] ---> [PingApps / Functions]",
  "  |",
  "  v",
  "Extension Bridge (WebSocket Server)",
  "  |",
  "  v",
  "Chrome Extension (Background Worker)",
  "  |",
  "  v",
  "Content Script (Browser Tab : DOM Operations, Extract, Navigate)",
  "```",
  "",
  "### LLM / Reasoning Flow",
  "```text",
  "Gateway (Self-Heal / Semantic Extract)",
  "  |",
  "  v",
  "Driver Registry (resolveStrategy: 'best')",
  "  |",
  "  v",
  "LLM Driver (Local Ollama/LMStudio OR Cloud Anthropic/OpenRouter)",
  "```",
  "",
  "## Onboarding Story",
  "",
  "When a new user begins using PingOS, the journey unfolds as follows:",
  "1. **Startup**: The user runs `npx pingos up`. The CLI spins up the `@pingdev/std` Gateway on port 3500 and launches Chrome with the local extension loaded.",
  "2. **Tab Sharing**: The user navigates to their desired site (e.g., Amazon, already logged in) and clicks the extension icon to 'Share' the tab.",
  "3. **Discovery**: The user runs `npx pingos status` to see connected devices. The extension bridge reports a `deviceId` (e.g., `tab-123`).",
  "4. **Action**: The user triggers an HTTP request: `POST /v1/dev/tab-123/extract { schema: { title: 'h1' } }`. The gateway routes this via WebSocket to the extension, the content script executes the query, and returns the result.",
  "5. **Advanced Automation**: The user can then invoke compiled PingApp functions: `POST /v1/functions/amazon/call { function: 'search', params: { query: 'shoes' } }`, completely abstracting away the browser tab details.",
  "",
  "## Configuration & Environment Variables",
  "",
  "PingOS uses `~/.pingos/config.json` for persistent settings, overridden by environment variables:",
  "",
  "**Core Networking:**",
  "- `PING_GATEWAY_PORT`: Port for the Fastify server (default 3500).",
  "- `PING_GATEWAY_HOST`: Host to bind to (default `::`).",
  "",
  "**LLM Providers:**",
  "- `OPENROUTER_API_KEY` / `OPENAI_API_KEY` / `ANTHROPIC_API_KEY`",
  "- `PINGOS_LLM_BASE_URL` & `PINGOS_LLM_MODEL`: Fallback OpenAI-compatible endpoint.",
  "",
  "**Local Mode (`PINGOS_LOCAL_MODE=true`):**",
  "- Limits DOM extraction size (`PINGOS_LOCAL_DOM_LIMIT`).",
  "- Adjusts timeouts (`PINGOS_LLM_QUERY_TIMEOUT_MS`, `PINGOS_LLM_HEAL_TIMEOUT_MS`).",
  "- Forces `jsonMode` for all LLM interactions.",
  "",
  "## Key Design Decisions and Patterns",
  "",
  "1. **Deterministic Fast Path:** PingOS relies on generated, static CSS selectors for interactions by default. This ensures execution latency is measured in milliseconds, bypassing LLM generation for standard operations.",
  "2. **JIT Self-Healing:** When a selector fails (DOM changed), the Gateway intercepts the error, extracts a context snapshot, asks an LLM to find the new selector, caches it locally, and retries the action transparently.",
  "3. **Tab-as-a-Device:** The system treats browser tabs like POSIX devices. The extension bridge registers tabs as connected clients. Operations are directed via `POST /v1/dev/:deviceId/:op`.",
  "4. **10-Level Smart Extract:** Extraction escalates gracefully. It starts with simple CSS queries, falls back to structural schema discovery, then semantic LLM querying, then JSON-LD structure parsing, and finally visual/screenshot extraction if the DOM is obscured.",
  "5. **POSIX Error Semantics:** Errors returned by the gateway follow standard UNIX codes like `ENOENT` (Not found), `EIO` (Input/Output Error - often used for DOM/WebSocket disconnects), and `ETIMEDOUT`, providing programmatic reliability.",
  "",
  "## Core API Endpoints",
  "",
  "### Device & Gateway Control",
  "- `GET /v1/health`: Gateway check.",
  "- `GET /v1/devices`: List all connected browser tabs.",
  "- `POST /v1/dev/:device/:op`: Execute an arbitrary operation (e.g., click, type, extract, recon) on a device.",
  "",
  "### Feature Engine",
  "- `GET /v1/dev/:device/discover`: Auto-analyze page layout.",
  "- `POST /v1/dev/:device/query`: Natural language question answering based on page context.",
  "- `POST /v1/dev/:device/diff`: Returns structural DOM differences for a schema between calls.",
  "- `POST /v1/dev/:device/watch/start`: Initiates Server-Sent Events (SSE) stream for DOM mutations matching a schema.",
  "",
  "### PingApp Routing",
  "- `GET /v1/functions`: List all registered app functions.",
  "- `POST /v1/functions/:app/call`: Call a predefined script sequence (e.g., `amazon.search`).",
  "- `POST /v1/app/:app/:action`: Direct application endpoints (e.g., `/v1/app/aliexpress/cart/add`).",
  "",
  "---",
  "",
  fileDocs
];

fs.writeFileSync('/home/rebelforce/projects/pingdev/CODEBASE-DEEP-DIVE.md', lines.join('\n'));
console.log('Successfully generated complete CODEBASE-DEEP-DIVE.md');
